# Showcase OSS
# OSS - no tag

FROM nginx:stable-alpine
MAINTAINER Johannes Sim
ENV REFRESHED_AT 2017-06-28
COPY  index.html *.png /usr/share/nginx/html/


# build:  docker build -t centricms/html .
# run:    docker run --name html -d -p 8090:80 centricms/html
# delete: docker rm -f html
# push:   docker push centricms/html
# pull:   docker pull centricms/html
# in:     docker exec -it html /bin/sh