# Showcase OSS
# OSS - no tag

FROM nginx:stable-alpine
MAINTAINER Johannes Sim / Remco Veldkamp
ENV REFRESHED_AT 2017-07-12
COPY  index.html *.png /usr/share/nginx/html/


# build:  docker build -t centricms/html .
# run:    docker run --name html -d -p 4200:80 centricms/html
# delete: docker rm -f  centricms/html
# push:   docker push centricms/html
# pull:   docker pull centricms/html
# in:     docker exec -it centricms/html /bin/sh