# Showcase dierentuin

version: "2.4"
services:
  konijn:
    image: centricms/konijn:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  dierenhok:
    image: centricms/dierenhok:spielerei
    volumes:
      - C:\TEMP\DATA\DIERENVOLUME:/dierenvolume
    depends_on: [konijn]
  dierentuin:
    image: centricms/dierentuin:spielerei
    ports: 
      - "4200:80"
    depends_on: [konijn]


# no config: docker-compose up -d
# local    : docker-compose -f docker-compose.yml -f local.yml up -d
# cloud    : docker-compose -f docker-compose.yml -f Sim001Docker.yml up -d
# down     : docker-compose down
