# Showcase .Net
# Application of 2 Docker containers

version: '3'
services:
  html:
    image: centricms/mvc:latest
    ports:
    - "5200:80"
    links:
    - webapi
  nodejs:
    image: centricms/webapi:latest
    ports:
    - "5300:80"

# no config: docker-compose up -d
# local    : docker-compose -f docker-compose.yml -f local.yml up -d
# cloud    : docker-compose -f docker-compose.yml -f Sim001Docker.yml up -d
# down     : docker-compose down 