# Showcase .Net
# DotNet - latest

FROM microsoft/aspnet:4.7
LABEL MAINTAINER="Johannes Sim / Renzo Veldkamp"
ENV REFRESHED_AT 2017-07-26

# build:  docker build -t centricms/mvc --build-arg site_root=/
# run:    docker run -d -p 5200:80 --name my-running-site centricms/mvc

# build:  docker build -t centricms/mvc .
# run:    docker run --name html -d -p 4200:80 centricms/mvc
# delete: docker rm -f  centricms/mvc
# push:   docker push centricms/mvc
# pull:   docker pull centricms/mvc
# in:     docker exec -it centricms/mvc /bin/sh